### ISSUE TITLE
Bad documentation in README?

### ISSUE THREAD

**Issue by guillemcordoba** [holochain/tryorama#30]
The documentation for tests with custom agent config and DNA is not working for me. 

`index.js`:

```js

const path = require("path");

const {
  Orchestrator,
  Config,
  combine,
  singleConductor,
  localOnly,
  tapeExecutor,
} = require("@holochain/tryorama");

process.on("unhandledRejection", (error) => {
  // Will print "unhandledRejection err is not defined"
  console.error("got unhandledRejection:", error);
});

const dnaPath = path.join(__dirname, "../dist/example-dna.dna.json");

const orchestrator = new Orchestrator({
  middleware: combine(
    // use the tape harness to run the tests, injects the tape API into each scenario
    // as the second argument
    tapeExecutor(require("tape")),

    // specify that all "players" in the test are on the local machine, rather than
    // on remote machines
    localOnly,

    // squash all instances from all conductors down into a single conductor,
    // for in-memory testing purposes.
    // Remove this middleware for other "real" network types which can actually
    // send messages across conductors
    singleConductor
  ),
});

const dna = {
  id: "rolesTests",
  file: "./dist/example-dna.dna.json",
};
const aliceConfig = Config.gen([{
  agent: {
    id: "alice",
    public_address:
      "HcScJWFagz6JtswwimIuXHa5V8h8Sjoy9Bkrbzfervjhuvq8g9whUEawSk845iz",
    file: "./alice.keystore",
  },
  dna,
}]);
const bobConfig = Config.gen([{
  agent: {
    id: "bob",
    public_address:
      "HcSCJR7dD9t6Nuqc9kxqWfKzbo443p8y8Z38IA9dukBEr96umt3b47uetMXg3aa",
    file: "./bob.keystore",
  },
  dna,
}]);

const {
  assignRole,
  getAgentRoles,
  getAllRoles,
  getAgentsWithRole,
  createEntry,
  unassignRole,
} = require("./utils");

orchestrator.registerScenario(
  "only progenitor can assign roles",
  async (s, t) => {
    const { alice, bob } = await s.players(
      { alice: aliceConfig, bob: bobConfig },
      true
    );
    const aliceAddress = alice.instance("rolesTest").agentAddress;
    const bobAddress = bob.instance("rolesTest").agentAddress;

    let result = await assignRole(bob)(aliceAddress, "editor");
    t.notOk(result.Ok);

    result = await assignRole(alice)(bobAddress, "editor");
    t.ok(result.Ok);
    await s.consistency();

    result = await getAgentRoles(bob)(bobAddress);
    t.equal(result.Ok[0], "editor");

    result = await getAgentsWithRole(bob)("editor");
    t.equal(result.Ok[0], bobAddress);

    result = await getAllRoles(bob)();
    t.equal(result.Ok[0], "editor");
  }
);

orchestrator.run();
```

Error:

```
  ]
}
14:33:49 [tryorama] error: Could not validate Instances Array
Tried to use an invalid value for a complex type and found the following problems:
    - Expecting string at 0.0.id but instead got: undefined.
    - Expecting string at 0.0.agent.0.name but instead got: undefined.
    - Expecting string at 0.0.agent.0.keystore_file but instead got: undefined.
/home/guillem/projects/eyss/holochain_roles/example-dna/test/node_modules/@holochain/tryorama/lib/types.js:22
        throw new Error(msg);
        ^
```

If I try to change the config to:

```js

const dna = {
  id: "rolesTests",
  file: "./dist/example-dna.dna.json",
};
const aliceConfig = Config.gen({
  agent: {
    id: "alice",
    public_address:
      "HcScJWFagz6JtswwimIuXHa5V8h8Sjoy9Bkrbzfervjhuvq8g9whUEawSk845iz",
    file: "./alice.keystore",
  },
  dna,
});
const bobConfig = Config.gen({
  agent: {
    id: "bob",
    public_address:
      "HcSCJR7dD9t6Nuqc9kxqWfKzbo443p8y8Z38IA9dukBEr96umt3b47uetMXg3aa",
    file: "./bob.keystore",
  },
  dna,
});
```

This is what I get:

```
14:39:25 info: 
☸☸☸ [[[CONDUCTOR combined]]]
☸ Error while trying to boot from config: ErrorGeneric("Error while trying to create instance \"agent--alice\": Holochain Instance Error: Attempting to initialize DNA with zero zomes!")
☸ 
14:39:25 [tryorama] info: conductor 'combined' exited with code 0
not ok 2 Conductor exited before starting interface (code 0)
  ---
    operator: fail
    stack: |-
      Error: Conductor exited before starting interface (code 0)
          at Test.assert [as _assert] (/home/guillem/projects/eyss/holochain_roles/example-dna/test/node_modules/tape/lib/test.js:228:54)
          at Test.bound [as _assert] (/home/guillem/projects/eyss/holochain_roles/example-dna/test/node_modules/tape/lib/test.js:80:32)
          at Test.fail (/home/guillem/projects/eyss/holochain_roles/example-dna/test/node_modules/tape/lib/test.js:322:10)
          at Test.bound [as fail] (/home/guillem/projects/eyss/holochain_roles/example-dna/test/node_modules/tape/lib/test.js:80:32)
          at /home/guillem/projects/eyss/holochain_roles/example-dna/test/node_modules/@holochain/tryorama/lib/middleware.js:72:19
          at processTicksAndRejections (internal/process/task_queues.js:93:5)
  ...
got an error for  agents can only create entries when given permission Conductor exited before starting interface (code 0)
14:39:25 [tryorama] debug: Done with test: agents can only create entries when given permission
```

**Comment by sdelvalle57** [comment]
Im also stuck in this issue, 
I do:
```
const aliceConfig = Config.gen([
  {
    id: 'alice',
    agent: {
      id: 'alice',
      name: "alice", 
      public_address: 'HcScijzE9x3Qjogoz9xOK4NjxFNthmf9br9ow8tN7PUb6djyAoWu5rKuhrsq93i',
      keystore_file: '../alice.keystore',
    },
    dna: {
      id: 'multisig',
      file: dnaPath,
    }
  },
])
const bobConfig = Config.gen([
  {
    id: 'bob',
    agent: {
      id: 'bob',
      name: "bob", 
      public_address: 'HcSCjoiU46sN787haaPA8z9QJ87WF64tx4agaka44D3dx7h8k45UdS9aPTF3koa',
      keystore_file: '../bob.keystore',
    },
    dna: {
      id: 'multisig',
      file: dnaPath,
    }
  }
])
```

```
What I get is:
22:08:58 info: 
☯☯☯ [[[CONDUCTOR alice]]]
☯ Unlocking agent keys:
☯ Unlocking key for agent 'alice': 
☯ Reading keystore from ../alice.keystore
☯ 
22:08:58 info: 
☸☸☸ [[[CONDUCTOR alice]]]
☸ Error while trying to boot from config: ConfigError("Could not load keystore \"../alice.keystore\"")
☸ 
22:08:58 [tryorama] info: conductor 'alice' exited with code 0
not ok 1 Conductor exited before starting interface (code 0)
  ---
    operator: fail
    stack: |-
      Error: Conductor exited before starting interface (code 0)
          at Test.assert [as _assert] (/home/holomachine/projects/holo-beefledger/dna/test/node_modules/tape/lib/test.js:228:54)
          at Test.bound [as _assert] (/home/holomachine/projects/holo-beefledger/dna/test/node_modules/tape/lib/test.js:80:32)
          at Test.fail (/home/holomachine/projects/holo-beefledger/dna/test/node_modules/tape/lib/test.js:322:10)
          at Test.bound [as fail] (/home/holomachine/projects/holo-beefledger/dna/test/node_modules/tape/lib/test.js:80:32)
          at /home/holomachine/projects/holo-beefledger/dna/test/node_modules/@holochain/tryorama/lib/middleware.js:72:19
          at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by sdelvalle57** [comment]
Ok, now I managed to load the keystore, but gets stcuk when it asks for the passphrase, so when I write down the passphrase no matter if it is empty or not, it doesn read from the console:

```
const dnaPath = path.join(__dirname, "../dist/dna.dna.json")
const alicePath = path.join(__dirname, "../alice.keystore")
const bobPath = path.join(__dirname, "../bob.keystore")

const orchestrator = new Orchestrator({
  middleware: combine(
    tapeExecutor(require('tape')),
    localOnly,
    singleConductor
  ),
})

const aliceConfig = Config.gen(
  [
    {
      id: 'aliceId',
      agent: {
        id: 'alice',
        name: "alice", 
        public_address: 'HcScijzE9x3Qjogoz9xOK4NjxFNthmf9br9ow8tN7PUb6djyAoWu5rKuhrsq93i',
        keystore_file: alicePath,
      },
      dna: {
        id: 'multisig-test',
        file: dnaPath,
      }
    },
  ],
)

const bobConfig = Config.gen(
  [
    {
      id: 'bobId',
      agent: {
        id: 'bob',
        name: "bob", 
        public_address: 'HcSCjoiU46sN787haaPA8z9QJ87WF64tx4agaka44D3dx7h8k45UdS9aPTF3koa',
        keystore_file: bobPath,
      },
      dna: {
        id: 'multisig-test',
        file: dnaPath,
      }
    }
  ],
)
```
What I get is:
```

22:57:39 info: 
☉☉☉ [[[CONDUCTOR combined]]]
☉ Using config path: /tmp/tmp.1paA6EI2zL/tryorama/4f7JBI/conductor-config.toml
☉ 
22:57:39 info: 
★★★ [[[CONDUCTOR combined]]]
★ Reading DNA from /home/holomachine/projects/holo-beefledger/dna/dist/dna.dna.json
★ 
22:57:39 info: 
☯☯☯ [[[CONDUCTOR combined]]]
☯ Reading DNA from /home/holomachine/projects/holo-beefledger/dna/dist/dna.dna.json
☯ 
22:57:39 info: 
☸☸☸ [[[CONDUCTOR combined]]]
☸ Unlocking agent keys:
☸ Unlocking key for agent 'alice--alice': 
☸ Reading keystore from /home/holomachine/projects/holo-beefledger/dna/alice.keystore
☸ 
22:57:39 info: 
☮☮☮ [[[CONDUCTOR combined]]]
☮ Passphrase: 
```

when I try the passphrase it doesnt continue and after some time it writes:

```
☉ DEBUG 2020-04-06 22:57:41 [holochain_locksmith::tracker] locksmith_guard_watcher/puid-0-0 crates/locksmith/src/tracker.rs:116 tracking 3 active guard(s) alive for > 1000ms:
☉ KIND       PUID      ELAPSED (ms)
☉ Lock   puid-0-2         1978
☉ Lock   puid-0-4         1906
☉ Lock   puid-0-3         1906
☉ DEBUG 2020-04-06 22:57:42 [holochain_locksmith::tracker] locksmith_guard_watcher/puid-0-0 crates/locksmith/src/tracker.rs:116 tracking 3 active guard(s) alive for > 1000ms:
☉ KIND       PUID      ELAPSED (ms)
☉ Lock   puid-0-2         2979
☉ Lock   puid-0-4         2906
☉ Lock   puid-0-3         2906
☉ DEBUG 2020-04-06 22:57:43 [holochain_locksmith::tracker] locksmith_guard_watcher/puid-0-0 crates/locksmith/src/tracker.rs:116 tracking 3 active guard(s) alive for > 1000ms:
☉ KIND       PUID      ELAPSED (ms)
☉ Lock   puid-0-2         3979
☉ Lock   puid-0-4         3906
☉ Lock   puid-0-3         3906
☉ DEBUG 2020-04-06 22:57:44 [holochain_locksmith::tracker] locksmith_guard_watcher/puid-0-0 crates/locksmith/src/tracker.rs:116 tracking 3 active guard(s) alive for > 1000ms:
☉ KIND       PUID      ELAPSED (ms)
☉ Lock   puid-0-2         4979
☉ Lock   puid-0-4         4907
☉ Lock   puid-0-3         4907
```

**Comment by sdelvalle57** [comment]
@guillemcordoba 
I found a workaround which is not the expected scenario but will do:
Turns out that with this configuration it wont spawn the keystore provided, but it will spawn a keystore which will set a constant agentAddress for each of the agents, have a look at the `console.log("alice instance add", alice.instance("alice_instance").agentAddress)` it will be always the same address. 

```
const dnaPath = path.join(__dirname, "../dist/dna.dna.json")
const alicePath = path.join(__dirname, "../alice.keystore")
const bobPath = path.join(__dirname, "../bob.keystore")

const orchestrator = new Orchestrator({
  middleware: combine(
    tapeExecutor(require('tape')),
    localOnly
  ),
})

const aliceConfig = Config.gen(
  [
    {
      id: "alice_instance",
      agent: {
        id: "alice_instance",
        name: "alice", 
        public_address: 'HcScijzE9x3Qjogoz9xOK4NjxFNthmf9br9ow8tN7PUb6djyAoWu5rKuhrsq93i',
        keystore_file: alicePath,
        test_agent: true,
      },
      dna: {
        id: 'multisig-test',
        file: dnaPath,
      }
    },
  ]
)

const bobConfig = Config.gen(
  [
    {
      id: 'bob_instance',
      agent: {
        id: 'bob_instance',
        name: "bob", 
        public_address: 'HcSCjoiU46sN787haaPA8z9QJ87WF64tx4agaka44D3dx7h8k45UdS9aPTF3koa',
        keystore_file: bobPath,
        test_agent: true,
      },
      dna: {
        id: 'multisig-test',
        file: dnaPath,
      }
    }
  ]
)

orchestrator.registerScenario("Scenario1: Start app", async (s, t) => {

  const { alice, bob } = await s.players(
    { alice: aliceConfig, bob: bobConfig },
    true
  );

  console.log("alice instance add", alice.instance("alice_instance").agentAddress)
  t.ok( alice.instance("alice_instance").agentAddress)
  console.log("bob instance add", bob.instance("bob_instance").agentAddress)
  t.ok( alice.instance("alice_instance").agentAddress)

  const start = await alice.call(
    "alice_instance", 
    M_ZOME, 
    "start", 
    { }
  )
  t.ok(start.Ok)
  await s.consistency();

})

```

**Comment by sdelvalle57** [comment]
Also, I was having some Timeout issues at the moment I wanted to link some entries, which I solved by running `sim2h_server -s O`

**Comment by jost-s** [comment]
@sdelvalle57 There's a new version released with a different API, hopefully more robust. You can check out if this issue still happens for you.
