### ISSUE TITLE
TypeError: Converting circular structure to JSON in orchestrator.run(): upgraded from 0.3.2-dev.3 to 0.3.4-dev.0

### ISSUE THREAD

**Issue by btakita** [holochain/tryorama#32]
After upgrading from `0.3.2-dev.3` to `0.3.4-dev.0`, a circular JSON structure occurs in `orchestrator.run()`

```
(node:410065) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'DerivedLogger'
    |     property '_readableState' -> object with constructor 'ReadableState'
    |     property 'pipes' -> object with constructor 'Console'
    --- property 'parent' closes the circle
    at JSON.stringify (<anonymous>)
    at Splatter._splat (/home/brian/work/cogov/cogov-dev/test/node_modules/logform/splat.js:71:25)
    at Splatter.transform (/home/brian/work/cogov/cogov-dev/test/node_modules/logform/splat.js:119:19)
    at Format.transform (/home/brian/work/cogov/cogov-dev/test/node_modules/logform/combine.js:20:24)
    at DerivedLogger._transform (/home/brian/work/cogov/cogov-dev/test/node_modules/winston/lib/winston/logger.js:305:29)
(node:410065) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
```

All of the assertions pass in test/index.js.

**Comment by jost-s** [comment]
@btakita There's a couple new versions out, please check if this problem still occurs.
